# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('boi', models.TextField(default='bio', max_length=300, null=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('project', models.ImageField(null=True, upload_to='links/')),
                ('views', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('posting', tinymce.models.HTMLField(null=True)),
                ('profiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='award.Profile')),
                ('user_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
