# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=20)),
                ('pic', models.ImageField(null=True, upload_to='pictures/')),
                ('comment', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('posting', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='image',
            name='profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='award.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
