# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_auto_20191030_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='posting',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
