# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20191031_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
